### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by dfaulken** [umts/incidents#1]

**Comment by werebus** [comment]
You or @sherson should check-in with someone at PVTA about this. **I** have a personal preference for MIT*, but its arguable that we're doing "work for hire" for them.

<sub>*well, actually, I prefer GPLv3, but a permissive license is the best choice for us as far as at being less likely to make someone mad/uncomfortable.</sub>

**Comment by sherson** [comment]
Yep, we will ask PVTA when we next talk to them (possibly next week).

**Comment by dfaulken** [comment]
We didn't ask PVTA, but I'm going with MIT for now rather than have it sit here unlicensed. This is an open card on Trello still.
