### ISSUE TITLE
Add latitude/longitude to incident reports

### ISSUE THREAD

**Issue by dfaulken** [umts/incidents#104]
Requested by Liza.

**Comment by dfaulken** [comment]
Discussed with Jamin and Maressa that their current process with PVTA claims is to use:

https://www.latlong.net/convert-address-to-lat-long.html

And copying and pasting.

Will see how to integrate on incidents.pvta.com.

**Comment by werebus** [comment]
That site turns out to just be a wrapper around the [Google Maps Geocoder API](https://developers.google.com/maps/documentation/javascript/geocoding).

**Comment by dfaulken** [comment]
That was what I figured. Need to decide if it's worth attempting something similar for this site, or merely having a link to that site (as PVTA claims does).
