### ISSUE TITLE
Why are the Travis tests so slow?

### ISSUE THREAD

**Issue by dfaulken** [umts/incidents#108]
At the time of writing, the whole test suite passes on my computer in 1 minute 20 seconds. On Travis, each test takes upwards of a minute to run.

This means that the suite fails for timing out.

**Comment by dfaulken** [comment]
Disabled Travis until we have some sort of answer here.

**Comment by mboneil10** [comment]
Currently running into a similar, but not quite as dramatic, problem on my machine. The whole suite ran in six minutes.

**Comment by werebus** [comment]
Works now?  I enabled Travis for #212 and everything seems fine there.
