### ISSUE TITLE
Bring drivers directly to PDF after submitting report

### ISSUE THREAD

**Issue by dfaulken** [umts/incidents#117]
Button should read 'Save and Print'.

May be possible to automatically trigger the printer dialog.

**Comment by werebus** [comment]
Easy to trigger the print dialog on an HTML document (`window.print()`, done), but quite a bit trickier with a PDF. The example, "Print an external page without opening it" [here][1] _might_ work, but only if there's in-browser, non-plugin, support for displaying PDFs.

[1]:  https://developer.mozilla.org/en-US/docs/Web/Guide/Printing
