### ISSUE TITLE
Continuous deployment

### ISSUE THREAD

**Issue by dfaulken** [umts/incidents#123]
Had requested a VM from Jim on 1/9. He mentioned in a text on 1/16 that he was working on it. He then mentioned in a separate thread on 1/22 that he had questions about it. That's the last that I heard.

**Comment by dfaulken** [comment]
I am not aware of any updates on this issue in the ensuing 20 months.

**Comment by sherson** [comment]
PVTA IT has so much on their plate that I don't think we're going to see any movement on this. So closing for now (will reopen if we think we/they can do it).
