### ISSUE TITLE
Handle incidents being deleted while people are filling out incident reports

### ISSUE THREAD

**Issue by dfaulken** [umts/incidents#149]
Currently causes an exception. Order of events is:

1. Driver/supervisor opens incident report to begin editing.
2. Admin deletes incident. Reports are not deleted (because of how they're defined).
3. Driver presses "Submit". Currently it's a 500. Report is saved, but incident no longer exists.

**Comment by mboneil10** [comment]
So the intended behavior is to prevent that driver from saving the report? Or is it okay that the report is saved?

**Comment by dfaulken** [comment]
We shouldn't be saving the report, since the incident no longer exists - it's stranded.

Could handle this two ways:

1. Controller logic with a guard clause that checks for incident presence, and redirects with a nice message if not.
2. Model validation that checks for incident presence, which will boot people back to the report edit page with a nice message.
