### ISSUE TITLE
Tests Intermittently Failing

### ISSUE THREAD

**Issue by mboneil10** [umts/incidents#156]
Could be order-dependent tests, timecop, or perhaps mocking? Idk needs to be looked into.

**Comment by mboneil10** [comment]
Reported by @werebus, too.

**Comment by dfaulken** [comment]
Yep, it's been an issue since about a month after there were automated tests. Everything was fine, and then out of the blue there started to be failures. Related to https://github.com/umts/incidents/issues/108

**Comment by mboneil10** [comment]
Yeah I think it's somehow related to `wait_for_ajax`, since that is involved in all the test failures.

**Comment by mboneil10** [comment]
For example, [this test](https://github.com/umts/incidents/blob/master/spec/system/supervisors/special_supervisor_report_fields_spec.rb#L89rspec) fails, and has the corresponding screenshot:
![test 1](https://user-images.githubusercontent.com/19267771/47237980-a624cd00-d3ae-11e8-8420-2f3744491e1c.png)

**Comment by mboneil10** [comment]
Perhaps it's taking a lot time to find the `Save Supervisor Report` button

**Comment by mboneil10** [comment]
Oh, no. It takes forever after clicking that button. :(

**Comment by mboneil10** [comment]
Figured it out. We need to `wait_for_animation!` every time a checkbox is checked or unchecked.

**Comment by werebus** [comment]
So, how important to our tests are those animations? Is it okay of they don't animate in test? If so...

https://api.jquery.com/jquery.fx.off/

Dumb (?) hack:

```haml
- #app/views/layouts/application.haml
- if Rails.env.test?
  :javascript
    jQuery.fx.off = true;
```

**Comment by mboneil10** [comment]
In my opinion, the animations (expanding and collapsing the accordion portions of the form) aren't that important. I'll make this change. Thanks @werebus.

**Comment by mboneil10** [comment]
capybara is making me angry. Still need to fix some more tests... Things like this happening occasionally:
```
  6) creating incidents as a driver brings drivers directly to the form
     Failure/Error: expect(page).to have_text 'Editing Driver Account of Incident'
       expected to find text "Editing Driver Account of Incident" in "All Incidents New Incident Logout Change Password Incident Reports You have no incident reports that need attention."
```
![image](https://user-images.githubusercontent.com/19267771/49885933-80440380-fe06-11e8-8b6e-1bf9566a68ee.png)

Looks like the page hasn't loaded when it's checking for that expectation. 😄

**Comment by mboneil10** [comment]
@anbranin recommended to adjust the `default_max_wait_time` for Capybara
