### ISSUE TITLE
Bus Number should be a Number

### ISSUE THREAD

**Issue by mboneil10** [umts/incidents#167]
Liza explained to me today that the `Bus #` submitted by the driver, supervisor, etc goes into the database as such. Say the number is entered as, for example, `Bus 1320` instead of something like `1320`. Those busses should be the same, but they aren't according to the database. 

I'm making this a question because I'm not sure if this is something worth doing. There is an example to the side of the field of what a bus number should look like.

**Comment by mboneil10** [comment]
I recently got this email from Liza:
 

> I just came across some UMass vehicles with the following Vehicle Numbers:
> <img width="104" alt="screen shot 2018-10-17 at 2 30 54 pm" src="https://user-images.githubusercontent.com/19267771/47108323-61b3f880-d219-11e8-9ec3-6669cf87c585.png">
> So this does not jive with what we were talking about earlier about entering “integers only” into the vehicle number fields.

**Comment by werebus** [comment]
Yeah, ultimately, nothing will insulate you from invalid data other than limiting users to a list of the only "correct" values. Same problem even if we only limit to integers: "3314" is a real bus, "3134" is not.

As an aside, though: "Car 2" and the like are examples of UMass Transit doing things differently than the rest of the PVTA for no particular reason. Service vehicles everywhere else are 4-digit numbers that start with a "9".

**Comment by Anbranin** [comment]
Right--I don't think it's appropriate to restrict it to integers only. I _do_ think it's appropriate to have the "vehicle number" the driver enters be a drop-down.

In any case you have, you would want to validate that the driver is entering a number of a vehicle that does in fact exist; if they pick from a list it prevents the problem entirely. The other thing to do would be to validate in the database and then spit back a warning if they get it wrong, but I would argue that that's a terrible user experience.

**Comment by Anbranin** [comment]
Didn't see @werebus's comment before I posted--I would add that I don't think we should always assume they'll be integers, even if they are now. What if we have to go to hexadecimal because there are so many vehicles...

**Comment by werebus** [comment]
But... I don't know that we have easy access to a list of all the valid PVTA vehicle names anywhere.

**Comment by dfaulken** [comment]
This is the exact conversation we had in the summer of 2017. A dropdown would be great to make sure we only get valid values, and it would be easier for people filling out the reports (just a reminder that they're not always 'drivers') - but where do we get that list?

**Comment by mboneil10** [comment]
@dfaulken, yes Liza mentioned that she had already talked to you about this. I wanted to put it up here on GH as a question to see if anyone could think of another way to do it.

**Comment by dfaulken** [comment]
IMO the best approach would be to decide which system (HASTUS/claims/incidents) will have the canonical list of valid vehicle names, and to automate a data feed between all three so that the lists are in sync.

**Comment by Anbranin** [comment]
Yes, the only thing that would work aside from restricting it to integers (which now seems fine that I realize there's no "vehicle" table like there is in round-three) is to have a list of vehicle names somewhere.

**Comment by dfaulken** [comment]
The next step here would be to determine whether there is an actual business requirement or technical issue being raised. If so, a design session between UMTS IT and PVTA IT would be required to determine best solution.

If not, I'd recommend closing this issue.
