### ISSUE TITLE
Incident Report Similarities and Copying

### ISSUE THREAD

**Issue by mboneil10** [umts/incidents#168]
Why don't the fields from the driver's account of the incident get copied over into the supervisor's account of the incident? Another question Liza brought up in a phonecall with me today.

**Comment by dfaulken** [comment]
There was never an ask for it. This should be run by the business users before we do any development work.

**Comment by mboneil10** [comment]
Okay, agreed.

**Comment by dfaulken** [comment]
This was requested in yesterday's meeting. I will reach out to Jamin and Dave with a list of fields common to both reports, and they will indicate which fields should be copied from complete supervisor accounts of incident to new driver accounts of incident.

**Comment by dfaulken** [comment]
Duplicate for #203.
