### ISSUE TITLE
Overflow page if description is too long

### ISSUE THREAD

**Issue by dfaulken** [umts/incidents#17]

**Comment by werebus** [comment]
Super easy, it turns out:  https://github.com/prawnpdf/prawn/blob/master/manual/text/text_box_excess.rb

**Comment by dfaulken** [comment]
Sorry, what I meant was the third page of the current PDF form:
<img width="593" alt="screen shot 2017-05-31 at 10 42 26 am" src="https://cloud.githubusercontent.com/assets/3988134/26637594/defe155a-45ed-11e7-9943-f3d2074ed851.png">

**Comment by werebus** [comment]
Ah, a page on which to write additional text.

For what it's worth, my link might be relevant if that narrative gets entered somewhere and the typeset text also overflows, I guess?
