### ISSUE TITLE
Time of Incident is off by Four Hours

### ISSUE THREAD

**Issue by mboneil10** [umts/incidents#170]
The `Time of Incident` on a printed Incident Report PDF is `6:30 am` and date as `10/17/2018`, but the `IncidentDate` in the database is `2018-10-17 10:30:00`. Why is there a two hour time difference?

**Comment by mboneil10** [comment]
<img width="790" alt="screen shot 2018-10-17 at 2 56 23 pm" src="https://user-images.githubusercontent.com/19267771/47109663-d89ec080-d21c-11e8-96e1-89fdd9f93633.png">

**Comment by mboneil10** [comment]
Shit, sorry just realized that's not something to put on GH.

**Comment by werebus** [comment]
4 hours, right? So time zones?

**Comment by mboneil10** [comment]
Aw dammit.
