### ISSUE TITLE
Empty Batch XML Export

### ISSUE THREAD

**Issue by mboneil10** [umts/incidents#172]
While working on #163, I've noticed that clicking the button `Select incidents to export...` will generate an empty XML file. It's in the coffeescript, so it seems to be an easy fix. Unless this was a requested feature. 
<img width="307" alt="screen shot 2018-10-19 at 12 17 54 pm" src="https://user-images.githubusercontent.com/19267771/47230731-0872d300-d399-11e8-96bb-a86c5508d097.png">

**Comment by dfaulken** [comment]
Nope, just an oversight.

**Comment by mboneil10** [comment]
Ok, will fix.
