### ISSUE TITLE
Injured Pax doesn't automatically check Incident involving Passenger

### ISSUE THREAD

**Issue by mboneil10** [umts/incidents#175]
`Did the incident involve a passenger?` checkbox is not checked by default even if passengers were injured.

**Comment by mboneil10** [comment]
Not sure if this was intended in order to reduce page clutter (the checkbox activates the accordion)

**Comment by mboneil10** [comment]
Totally confused. This might be happening occasionally

**Comment by mboneil10** [comment]
Ah, so it happens when saving portions of the driver account of incident, but not all (`Bus #`, `Location`, `Town`, etc.). The entries for the injured pax are filled in, but there's an error so the report isn't saved.

**Comment by dfaulken** [comment]
That's interesting. Don't we use nested attributes? I'm surprised that if an update fails to the parent object, Rails doesn't just rollback the whole transaction.

**Comment by mboneil10** [comment]
Yes, we use nested attributes. I'm surprised, too. Do you think I should look into fixing this @dfaulken?

**Comment by dfaulken** [comment]
I do. Hopefully it will be a small fix once we can figure out why nested attributes aren't working the way we think they ought to.

**Comment by dfaulken** [comment]
Next step here is to investigate whether this issue is still occurring, and if so, try to determine root cause.
