### ISSUE TITLE
Test downloads in my actual Downloads folder

### ISSUE THREAD

**Issue by werebus** [umts/incidents#177]
Just a minor annoyance, but the test suite in this apps clogs my `Downloads` folder with a bunch of random XML and CSV files.

My opinion is that "downloads" might be better tested with a request spec, but I'm pretty sure that's a minority opinion. Otherwise, it might be nice to modify Chrome to download to some temporary location.

Relevant: https://stackoverflow.com/a/47283609

**Comment by dfaulken** [comment]
Nice find. Definitely agreed.
