### ISSUE TITLE
Google Maps API

### ISSUE THREAD

**Issue by mboneil10** [umts/incidents#186]
I've done about half the job for this (generated an incidents API key with correct restrictions) on the PVTA Developer account, but it still needs to be implemented.

**Comment by dfaulken** [comment]
@mboneil10 were you able to document the work you did for this?

**Comment by mboneil10** [comment]
@dfaulken what do you mean by "document" (shudders)? Do you mean the general process for how I set up the API key in the code or on the website? Or?

**Comment by dfaulken** [comment]
Yes. What did you do so far, and what still needs to be done? Just more detail would be good.

**Comment by mboneil10** [comment]
So everything that I did should be on the PVTA Developer account. What I mean by "it needs to be implemented" is changing the code so it can work with the new API keys. Does that make sense?
