### ISSUE TITLE
Session timeout warning

### ISSUE THREAD

**Issue by dfaulken** [umts/incidents#192]
Dave Klingener email on 5/2:

> Also, I was wondering if we could eliminate the time-out feature or lengthen it significantly. We have had an instance of someone completing a report and taking quite a while, then it deleted everything after he hit submit.

My response:

> I believe the timeout is configurable, though we should consider the security implications of lengthening the window. For instance, if a user were to walk away from a computer without logging out, a longer timeout would increase the likelihood of their data being compromised. What I might suggest is that we look into a way to have any activity on the site reset the timeout (mouse movement, keyboard activity, etc.), rather than having to navigate between pages or submit a form to reset the timeout. Then the only thing that would cause a timeout would be a user not interacting with the site at all for the same period of time.

Dave's reply:

> And yes, that sounds like a good compromise to adjusting the time-out – having mouse / keyboard activity keep resetting the timer.

It seems like what would work instead is having a Javascript message warning that a session is about to expire, with a built-in "Extend my session" button. Something like [this StackOverflow post](https://stackoverflow.com/questions/17791626/devise-make-a-request-without-resetting-the-countdown-until-a-user-is-logged-o) would work for the Devise side, and we could design the JS code fairly easily.

**Comment by dfaulken** [comment]
Doesn't seem that easy to do with JS, really. Timeout was extended, and we'll see if we hear more about this.

**Comment by sherson** [comment]
While meeting at SATCo, Dave K said that this hasn't been an issue since the extended timeout. They'll let us know if there are any issues; will reopen if needed.
