### ISSUE TITLE
Supervisors who don't conduct D/A tests have to check the box saying a test was conducted

### ISSUE THREAD

**Issue by dfaulken** [umts/incidents#194]
Dave Klingener email on 5/2:

> If a drug-testing threshold is met, but the supervisor decides not to drug-test because he / she is discounting the driver, they will have to first check “completed drug / alcohol test” then check the threshold that was met, then uncheck “completed drug / alcohol test to make the notification fields disappear. Then they will have to complete the reason they are discounting the driver description box. Is there any way we can stream-line this by separating the threshold checkboxes as their own field that does not disappear ever? If they decide not to drug test due to discounting the driver, they are missing the threshold checkboxes completely because they are never being opened via the completed drug test check box.

**Comment by dfaulken** [comment]
Reading through this one, I'm confused. If a supervisor is completely discounting the driver, that field is still available even if they do not check "completed drug or alcohol test":

<img width="1187" alt="Screen Shot 2019-05-25 at 1 51 43 PM" src="https://user-images.githubusercontent.com/3988134/58373001-4ec27e80-7ef4-11e9-9c98-d364e07e3aaa.png">

But all of the fields that they see if they *do* check that box only apply if a test was actually conducted:

<img width="739" alt="Screen Shot 2019-05-25 at 1 51 59 PM" src="https://user-images.githubusercontent.com/3988134/58373004-5c780400-7ef4-11e9-9cab-f5c9aaafb10f.png">

So I don't understand why a supervisor would need to fill out any of those fields, if they're discounting the driver anyway.

Need more information from Dave K.

**Comment by sherson** [comment]
We met about this at SATCo (Missy, Dave K, me, and Jamin called in), reviewed their workflow, and determined what we should do on the input form is remove Completed Drug or Alcohol Test altogether, and remove Post Accident and Reasonable Suspicion. 

Instead, we should have one pull down selection box with four choices:

* Post Accident: Threshold met (completed drug test)
* Post Accident: No threshold met (no drug test)
* Post Accident: Threshold met and discounted (no drug test)
* Reasonable Suspicion: Completed drug test 

Missy said we don’t need to change what comes up on the input form after that, except that no testing timeline fields need to be filled out if no drug test need to be on input form, but they do need to be on the PDF.

The PDF is fine as is, as long as the supervisor:

* Selects Post Accident: Threshold met and discounted (no drug test)
* Explains why in text field
* Checks off which of the three thresholds (bodily, disabling, fatality)
