### ISSUE TITLE
Injured passengers / witnesses don't appear in PDF

### ISSUE THREAD

**Issue by dfaulken** [umts/incidents#202]
Melissa R:

> They are able to add them but when printed, the information does not appear.

**Comment by dfaulken** [comment]
Can't replicate.

**Comment by dfaulken** [comment]
Jamin specified production incident ID 241 has this issue.

**Comment by dfaulken** [comment]
241 didn't actually have the issue. Dave K specified 631 which does.

**Comment by dfaulken** [comment]
confirmed resolved.

**Comment by sherson** [comment]
@dfaulken this seems to be fixed for new incidents, but the old incidents still don't show the additional witnesses. Do we have that data or is is lost?
