### ISSUE TITLE
Copy fields from supervisor report to driver report

### ISSUE THREAD

**Issue by dfaulken** [umts/incidents#203]
Sent field list to Jamin. Need his input on which should be copied. Then need to figure out how to do it.

**Comment by sherson** [comment]
Jamin sent us a list; @dfaulken is going to review and confirm with Dave K.

**Comment by dfaulken** [comment]
Forwarded Jamin's list to Dave K today.

**Comment by dfaulken** [comment]
Jamin's list was:

![image](https://user-images.githubusercontent.com/3988134/65642784-0e682f80-dfbe-11e9-9871-dddbfe68e592.png)

**Comment by Anbranin** [comment]
I came here because @sherson complained that there was a picture of some text. Now I've seen it and wish to leave.

**Comment by dfaulken** [comment]
Sorry yes, I guess that's the weird thing that Microsoft Word decided to do
when I copied and pasted.
