### ISSUE TITLE
Fields in claims but not in incidents

### ISSUE THREAD

**Issue by dfaulken** [umts/incidents#204]
Jamin / Dave K to send us a list.

**Comment by dfaulken** [comment]
I don't believe we've received this. Once we have this input, we would then add the DB fields, add to the show/edit views, add to the claims export, and determine whether necessary to add them to the PDF.

**Comment by sherson** [comment]
I called Jamin and mentioned we didn't think we'd gotten this (or if I did, it got lost in my tsunami of an inbox). He doesn't think he sent it, and will get it to us shortly.

**Comment by werebus** [comment]
I _think_ this is done in #249.
