### ISSUE TITLE
Make changes to testing timeline portion of Supervisor Report (input screen)

### ISSUE THREAD

**Issue by sherson** [umts/incidents#206]
A couple sequence of events are missing or need to be changed. SATCo/VATCo asked this to be included at the end of the Testing Timeline portion (using same year month day hour minute fields) in the same email thread as #194:

> We are missing sequence of events criteria:
> 
> Missing:
> 
> * Time when union/ other employee rep was contacted (person notified ______________)
> * Arrival time at Testing facility/time mobile testing team arrives on location.
> * Arrival time of union rep, if applicable.
> * The only ability to see any of the post-accident testing information is by clicking that there was a collision.
> 
> To be changed:
> 
> * “Employee Returned” change to “Time Employee returned to work or released from duty”

(that last one is actually “Employee returned at”)

**Comment by dfaulken** [comment]
> The only ability to see any of the post-accident testing information is by clicking that there was a collision.

This bullet point ought to be a separate issue, and not addressed in this one, though I believe there is already a related item.

As it stands, this is a relatively low-hanging fruit:

+ add the necessary DB fields
+ add to the show/edit pages
+ add to the PDF

**Comment by avacmeyer** [comment]
Can you have a drug test without there being a collision? Otherwise I don't see a point in making the ability to see all testing timeline info dependent upon whether or not there was a collision. Its current all dependent upon the "Completed drug or alcohol test?" checkbox. Alternatively I can just replace this checkbox with a "Was there a collision" checkbox.

**Comment by Anbranin** [comment]
Are you asking if it's possible to drug test a bus driver even if they haven't gotten into an accident? I would assume that the answer is yes, because of all the times I heard about "reasonable suspicion" when I started working at Transit.

**Comment by avacmeyer** [comment]
I agree but I'm wondering if they use incidents for drug tests regarding reasonable suspicion.

**Comment by avacmeyer** [comment]
The drop down for reason_test_completed includes reasonable suspicion so I guess that answers that.

**Comment by Anbranin** [comment]
I believe the answer to be immaterial anyway. It seems like they asked for the ability to be able to see the post-accident testing information without having to check that there was a collision and we should just do that for them, because there are many things to consider we may not think of, like that in their conception not all accidents might be marked as a collision.

**Comment by werebus** [comment]
Huh. I kinda thought that their request was the exact opposite of that (since you already can have a post-accident test on a non-collision)

@sherson, any chance of clarifying what you meant here?

**Comment by werebus** [comment]
That is, I read that last bullet as a the desired functionality, not a description of undesired functionality.

**Comment by Anbranin** [comment]
What a weird way to state desired functionality, but if one takes it literally that is what they're saying.

**Comment by werebus** [comment]
Yeah, it's included in a list of things that are "Missing" (I guess?).

But what pushed it over the line for me was that, if it was a bug description, there's nothing to be done. The app already works that way: There is currently no connection between whether the incident is a "collision" and whether a "post-accident" test was completed.

**Comment by avacmeyer** [comment]
So should add this option or ignore it?

**Comment by werebus** [comment]
Here's what I would do:

1. Create a separate issue for that one bullet (like @dfaulken initially suggested)
2. Do everything else requested in _this_ issue (the requested timeline fields)
3. Reach out to stakeholders for clarification

Might also be a good idea to finish up #194 (issue) / #210 (PR)

**Comment by sherson** [comment]
The text in question was from an email from Melissa Rowe. Given how long it's been, we should confirm what she meant, and if anything has changed. I'll email her today.

**Comment by dfaulken** [comment]
>The only ability to see any of the post-accident testing information is by clicking that there was a collision.

This was a statement of "this is true and I would like it not to be true"

**Comment by werebus** [comment]
OK, but it isn't true, so... nothing needs to be done?

**Comment by sherson** [comment]
Ava emailed her about this (and another issue) last week. I called Melissa this morning and she has understandably been busy with other things. I told her no rush.
