### ISSUE TITLE
Occasional test failure in system test

### ISSUE THREAD

**Issue by werebus** [umts/incidents#216]
Tests in `spec/system/supervisors/special_supervisor_report_fields_spec.rb` occasionally fail.

They're all related to the drug and alcohol testing fields in some way, and I think it's due to the fact that the `:supervisor_report`factory is so chock-full of randomness:

https://github.com/umts/incidents/blob/1c08c732338969da5ab2d7a737f1d9fda8710d9b/spec/factories/supervisor_reports.rb#L8-L11

https://github.com/umts/incidents/blob/1c08c732338969da5ab2d7a737f1d9fda8710d9b/spec/factories/supervisor_reports.rb#L32-L55

So, for a given Factory Bot-created incident, maybe a reason for discounting was given maybe it wasn't.

**Comment by Anbranin** [comment]
@Tanvish is experiencing problems with this fact right meow.

**Comment by Anbranin** [comment]
@Tanvish also the tests just simply fail on master due to one of your other PRs. I'd like you to just fix this before doing anything else--sick of having your builds not pass because of something so simple.

**Comment by Tanvish** [comment]
> @Tanvish also the tests just simply fail on master due to one of your other PRs. I'd like you to just fix this before doing anything else--sick of having your builds not pass because of something so simple.

Made a new PR and fixed it. (hopefully)

**Comment by Tanvish** [comment]
> Tests in `spec/system/supervisors/special_supervisor_report_fields_spec.rb` occasionally fail.
> 
> They're all related to the drug and alcohol testing fields in some way, and I think it's due to the fact that the `:supervisor_report`factory is so chock-full of randomness:
> 
> https://github.com/umts/incidents/blob/1c08c732338969da5ab2d7a737f1d9fda8710d9b/spec/factories/supervisor_reports.rb#L8-L11
> 
> https://github.com/umts/incidents/blob/1c08c732338969da5ab2d7a737f1d9fda8710d9b/spec/factories/supervisor_reports.rb#L32-L55
> 
> So, for a given Factory Bot-created incident, maybe a reason for discounting was given maybe it wasn't.

#210 has some changes that possibly fix this.

**Comment by jforgue** [comment]
This is an issue with tests in `/spec/system/drivers/editing_incidents_spec.rb` as well.

**Comment by werebus** [comment]
> This is an issue with tests in /spec/system/drivers/editing_incidents_spec.rb as well.

That turned out to be a _different_ issue, #257
