### ISSUE TITLE
Indication that form is filled out

### ISSUE THREAD

**Issue by sherson** [umts/incidents#25]
Should there be an indication to staff that a driver has filled out an incident? Related: when the driver saves, should they indicate whether or not they actually finished filling out the form (perhaps this is an edge case, but it's conceivable that a driver might partly fill out the description and want to save and come back later to finish it).

Loosely related to #16

**Comment by dfaulken** [comment]
My inclination is to not add complexity that hasn't been requested.

**Comment by dfaulken** [comment]
Hasn't been requested since.
