### ISSUE TITLE
500 on incidents show page if reason code is `nil`

### ISSUE THREAD

**Issue by werebus** [umts/incidents#250]
https://github.com/umts/incidents/blob/25ead81ffb5aa884704d36ef991a7426b207ea03/app/views/incidents/show.html.haml#L32

A reason code isn't required for incidents; this line needs `nil`-handling.

**Comment by avacmeyer** [comment]
I'm having trouble replicating this issue.

**Comment by werebus** [comment]
I created this issue because someone _did_ get this exception in production:

<details>

    An ActionView::Template::Error occurred in incidents#show:

    undefined method `full_label' for nil:NilClass
    app/views/incidents/show.html.haml:32:in `_app_views_incidents_show_html_haml___1781289192561207787_70231081645720'


    -------------------------------
    Request:
    -------------------------------

    * URL : https://incidents.pvta.com/incidents/371
    * HTTP Method: GET
    * IP address : [REDACTED]
    * Parameters : {"controller"=>"incidents", "action"=>"show", "id"=>"371"}
    * Timestamp : 2020-05-20 14:48:06 -0400
    * Server : UmassDev1
    * Rails root : /srv/incidents/releases/20200430205955
    * Process: 16903

    -------------------------------
    Backtrace:
    -------------------------------

    app/views/incidents/show.html.haml:32:in `_app_views_incidents_show_html_haml___1781289192561207787_70231081645720'
    app/controllers/incidents_controller.rb:122:in `block (2 levels) in show'
    app/controllers/incidents_controller.rb:120:in `show'

</details>

Looking at it further, that production incident is, indeed, invalid:

```ruby
i=Incident.find(371)
i.valid?
#=> false
i.errors.messages
#=> {:reason_code=>["can't be blank"], :supplementary_reason_code=>["can't be blank"], :root_cause_analysis=>["can't be blank"], :latitude=>["can't be blank"], :longitude=>["can't be blank"]}
```

All of those fields  are _conditionally_ validated if the incident is `completed`. Somehow, the incident was made `completed` without being validated.  I can also tell you that there are 105 such invalid incidents in production.

It _could_ be that its not reproducible now. Probably "someone" should figure out what to do with those invalid incidents, though.
