### ISSUE TITLE
Remove column citation information taken from incident reports model

### ISSUE THREAD

**Issue by avacmeyer** [umts/incidents#251]
This column exists in claims, but I realize that I can use the field summons_or_warning_issued that already exists in the incident_report model.

**Comment by Anbranin** [comment]
You say that you can "use the field" but for what? Why did citation_information_taken exist in the first place? From a user endpoint what does this accomplish?

**Comment by avacmeyer** [comment]
It is a field that exists in claims but doesn't in incidents under the same name. It needs to be part of the xml file export to claims.

**Comment by Anbranin** [comment]
Oh so summons_or_warning_issued has the same value as citation_information_taken, so two of them are extraneous?

**Comment by avacmeyer** [comment]
Yes they have the same value. Liza had the value citation_information_taken on her list for the claims export so I added it to incidents with the other missing fields. I realized later that summons_or_warning_issued is literally the same thing so I then removed citation_information_taken.

**Comment by werebus** [comment]
Closed by #249
