### ISSUE TITLE
Add missing fields from claims to incident xml file

### ISSUE THREAD

**Issue by avacmeyer** [umts/incidents#254]
A xml file has been requested for an export from incidents to claims. The xml file exists but needs to have its fields changed to match the information that is needed for an export. Attached are fields requested for the xml. 
<img width="640" alt="Screen Shot 2020-06-21 at 7 40 45 PM" src="https://user-images.githubusercontent.com/28609962/85237759-4094a980-b3f7-11ea-9e40-3a2906fa214d.png">
<img width="631" alt="Screen Shot 2020-06-21 at 7 41 11 PM" src="https://user-images.githubusercontent.com/28609962/85237761-44c0c700-b3f7-11ea-8e97-2d7c42559e9d.png">
<img width="631" alt="Screen Shot 2020-06-21 at 7 41 17 PM" src="https://user-images.githubusercontent.com/28609962/85237764-48544e00-b3f7-11ea-9b11-c6072aac0a00.png">

**Comment by werebus** [comment]
Closed by #255
