### ISSUE TITLE
Travis failing due to coverage drop

### ISSUE THREAD

**Issue by jforgue** [umts/incidents#265]
Travis' coverage reporter seems to calculate the coverage differently than our local machines.
```
Coverage report generated for RSpec to /home/travis/build/umts/incidents/coverage. 674 / 798 LOC (84.46%) covered.
Coverage has dropped by 0.12% since the last time (maximum allowed: 0.00%).
SimpleCov failed with exit 3
The command "bundle exec rspec" exited with 3.
```

**Comment by werebus** [comment]
Travis runs your test suite on the _result_ of the merge. And, indeed, withe the last few PRs now merged, there is now a drop of %0.12 on `master` (which is a little less than one line if there are 798 LOC :grey_question: ).

Honestly, failing the entire build for such an insignificant drop seems too rigid to me.

**Comment by jforgue** [comment]
If we look at PR #264 there's only one line that's changing and it's in the `config` directory. Shouldn't that be filtered out? I wouldn't expect coverage to change here at all, or maybe I misunderstand how it does the calculation?

**Comment by jforgue** [comment]
Of course, as I say that it passes. But that is the result of it running a third time. It failed the first run when the code was identical.

**Comment by werebus** [comment]
The issue here is that the coverage dropped legitimately due to some PR where someone didn't run the specs. That drop was ignored, and the `.last_run.json` file remained falsely high. When Travis merges your PR and then runs RSpec, SimpleCov only sees that the coverage is lower than what was _stored_ in the repo.

**Comment by werebus** [comment]
But again, I also don't care.
