### ISSUE TITLE
Use deliver_later

### ISSUE THREAD

**Issue by avacmeyer** [umts/incidents#289]
When created a new incident we use deliver_now to send messages to supervisors notifying them of new incidents. Since this can sometimes take a very long time to complete, we can use deliver_later instead.

**Comment by werebus** [comment]
Also note that this will require setting up a background job system. UMTS has experience with Sidekiq (on umaps-rails) and Resque (on round-three).

I can put the server configuration half of things on my to-do list.

**Comment by werebus** [comment]
Redis and Sidekiq are set up and running in prod. I did the following in the console:

```ruby
 ApplicationMailer.with(incident: Incident.first, destination: 'me@myemailaddress.example.com').new_incident.deliver_later
```

And received the notification email.
