### ISSUE TITLE
Map missing from incident report form with no starting location

### ISSUE THREAD

**Issue by sherson** [umts/incidents#314]
Received today from Jamin:

> Good morning,
> 
> Just want to let everyone know that about a week ago, a VATCo Supervisor noticed that the map was missing from the incident report screen and that on one occasion, the map did display, but the Lat and Long did not autocomplete. Please see the screenshot for reference.

![incidents-missing-map](https://user-images.githubusercontent.com/409008/122976399-4acaea00-d362-11eb-85ca-cd533fa0b994.png)

**Comment by werebus** [comment]
In cases where there isn't a location when the page is loaded, the JS errors out:

```
Uncaught TypeError: results is null
```

https://github.com/umts/incidents/blob/6c289a11b9e48d3af3092a645debb4b88849e820/app/assets/javascripts/latlong_map.coffee#L27
