### ISSUE TITLE
Remove "Amplifying comments"

### ISSUE THREAD

**Issue by sherson** [umts/incidents#325]
SATCo requested the following for the Incidents edit form:

1. Adjust the edit form to always have the _"Test status"_ data entry box. Currently it appears for all choices other than _"Post Accident: Threshold met (completed drug test)"_.
2. Remove _"Amplifying comments"_ altogether.
3. Rename _"Amplifying comments"_ to _"Test status"_ on the PDF report.

Waiting to hear back as to whether or not we need to concatenate the "Test status" and "Amplifying comments" fields into "Test status", perhaps with a separator and label such as:

```
[Test status content]
------------------------
Amplifying comments:
------------------------
[Amplifying comments content]
```

**Comment by bandogora** [comment]
1. When you say the "edit form" what page are you talking about specifically? The edit form _should_ always display a "Test status" select box.

2. Are "Amplifying comments" not used at all, or do you want them to go under the "Test status" section? I'm guessing you want to remove the "Amplifying comments" label and not the actual comments.

**Comment by sherson** [comment]
Another box (text area not pull-down selection box) appears below the `Test Status` box depending on what is chosen in `Test Status`.

They said to remove both the `Amplifying comments` label and comments.

@werebus pointed out there are actually two different text areas the correspond to different `Test Status` selections. One of them appears to not be included on the PDF. 

Also, the text area must be filled out for certain situations, which is probably why it was written to only sometimes appears. We need to confirm the requirements and how PVTA wants it to work.

**Comment by bandogora** [comment]
From the SATCO emails:

Test status|Text area|Text area description
|----|-----|----|
[blank]|No|-
Post Accident: Threshold met (completed drug test)|Yes|Please list which FTA threshold(s) were met.
Post Accident: No threshold met (no drug test)|Yes|Please explain how the TFA threshold is not met.
Post Accident: Threshold met and discounted (no drug test)|Yes|Please explain why the driver can be discounted.
Reasonable Suspicion: Completed drug test|Yes|Please document any relevant information or observations that led to the decision to initiate testing.

> Either way, we assume the last page of the PDF should include whatever was entered into the text area for Test status. Is that correct?

Yes.

[We have] also requested that the description on the current last page still show up when the page is generated if that is possible.
![image](https://user-images.githubusercontent.com/26842354/146979995-9d48f08a-da17-4c26-bf27-f44a0b1e5b16.png)
