### ISSUE TITLE
Field mismatch with upgraded Hastus

### ISSUE THREAD

**Issue by werebus** [umts/incidents#342]
PVTA's install of Hastus was recently upgraded from version 2015 to version 2021. We were informed that there's a discrepancy between a field in our Hastus export and what Hastus now expects.

In Hastus, "preventability" was previously stored in `` `accident_incident`.`ai_is_preventable` `` and was a boolean value. Now it is stored in `` `accident_incident`.`ai_preventability` ``, and is a.... enum?, text?, integer? In the **UI** it's presented as a drop-down:

![image001](https://user-images.githubusercontent.com/240275/164281873-78e62e63-b41d-4331-b77b-dca270e0422e.png)

This line:

https://github.com/umts/incidents/blob/c354a738a927869c202abf6f83789cf27c9274f6/app/views/incidents/_incident.xml.haml#L20

Needs to be changed to match the new Hastus schema.

---

VATCo and PVTA confirmed that they (probably) don't need the additional choices added into this app — they're going to check in with the primary user of the PVTA claims DB in case they want to add the other kinds of preventability to _their_ system. As long as that's the case, it should stay as a boolean in this app.

---

We're also waiting to find out what the data format Hastus actually needs.

**Comment by sherson** [comment]
We were told that there is no need to change what goes into the Claims system.

The specifications document we received doesn't actually cover this. For what it's worth, Hastus shows:

![Hastus Incidents Preventable field](https://user-images.githubusercontent.com/409008/164727933-6c5bb274-7dd4-4d0c-aecf-5f2513e53b6a.png)

Not sure what `Data type: Specific` means.

Working on getting more complete specifications. In the meantime, perhaps we could try exporting text that matches what's in the first screen-cap?:

`Preventable`
`Non-preventable`

**Comment by werebus** [comment]
Perhaps an existing file that was failing to import?

**Comment by sherson** [comment]
This fell off PVTA's radar for a while, but we finally got an answer (it appears to only work if it's ALL CAPS): 

``` xml
<ai_preventability>NON_PREVENTABLE</ai_preventability> 
<ai_preventability>PREVENTABLE</ai_preventability>
