### ISSUE TITLE
Anyone should be able to print anything at any time

### ISSUE THREAD

**Issue by dfaulken** [umts/incidents#40]
But also we should track when things are printed. Can one create versions with custom events other than `create`, `update`, `destroy`?

**Comment by dfaulken** [comment]
Also when marked as completed (for Hastus, can just be a single timestamp).

**Comment by werebus** [comment]
So, maybe this would work?

```ruby
report.paper_trail_event = 'print'
report.touch
report.paper_trail_event = nil
```
