### ISSUE TITLE
Towns drop down list

### ISSUE THREAD

**Issue by sherson** [umts/incidents#54]
Would like towns to be from list or autocomplete and enforce correct spelling. But some edge cases with multiple towns or outside of service area (mechanic goes to CT for something), so list needs "Other" and they can put the town in a different field-

**Comment by dfaulken** [comment]
What are all the towns that VATCo and SATCo service?

**Comment by sherson** [comment]
Can probably get from Hastus. I'd ask Jamin and Dave K to provide those lists.

**Comment by dfaulken** [comment]
Emailed Jamin and Dave K.
