### ISSUE TITLE
Move system tests over to RSpec

### ISSUE THREAD

**Issue by dfaulken** [umts/incidents#6]
Pending https://github.com/rspec/rspec-rails/pull/1813, which will allow for using the Selenium webdriver in RSpec, rather than with MiniTest.

**Comment by dfaulken** [comment]
Removed the tests today. https://github.com/umts/incidents/commit/9438daa1d86db22a1bb88b2aed8c13d2784a882f

Should rebuild from the ground up using rspec-rails, once the software specifications are stable.

**Comment by dfaulken** [comment]
Have started rebuilding. Shouldn't close this issue until we're at 100% coverage.

**Comment by dfaulken** [comment]
Good progress so far, about 80% coverage. Before we put CI into place, though, there are a few JS-dependent tests which fail about half of the time, despite various solutions I've tried to allow for time for animations to happen, to wait for background AJAX requests, etc. We should get these tests so that they're reliable, or figure out a way of configuring acceptable vs. unacceptable failures, before instituting CI.

**Comment by Anbranin** [comment]
I can't wait to see how you get CI into place, since my programmers have had such trouble with it. Are you going to open a PR so we can look at what you've done or are you not at that point?

**Comment by dfaulken** [comment]
The setup I had in place before used Firefox. https://github.com/umts/incidents/blob/72a397db270c990c39ce9339994037727f79a611/.travis.yml

**Comment by dfaulken** [comment]
CI is set. The trick to making the tests consistently pass was to retry failed examples, allowing for more time for animations to complete.
