### ISSUE TITLE
Password login with default password for drivers

### ISSUE THREAD

**Issue by dfaulken** [umts/incidents#68]
Jamin pointed out that while there's no real incentive for drivers to log in as each other, badge number + last name isn't secure enough for staff, who have access to sensitive data.

Proposed implementing a system where staff would have to change their passwords, which would by default be their last name.

Should run by the group before implementing.

**Comment by sherson** [comment]
Emailed the group yesterday (we shouldn't have agreed to getting rid of the password in the first place).

**Comment by dfaulken** [comment]
No one in the group dissented.

**Comment by dfaulken** [comment]
We'll need a rake task to set everyone's default passwords.
