### ISSUE TITLE
Attach cover sheet to VATCo PDFs

### ISSUE THREAD

**Issue by dfaulken** [umts/incidents#74]
Jamin sent us a cover sheet which he would like to be included at the beginning of VATCo incident forms.

**Comment by dfaulken** [comment]
This hasn't been requested since. The next step would be to follow up to determine whether it's still a genuine business requirement, in which case it would be a simple matter of hardcoding the page into the PDF with some conditional logic for whether the driver/supervisor comes from the particular division.

**Comment by avacmeyer** [comment]
Where can I find this cover sheet? I can email Jamin for followup.

**Comment by dfaulken** [comment]
Yes, recommend emailing Jamin to get an updated copy.
