### ISSUE TITLE
Export XML should download rather than display inline

### ISSUE THREAD

**Issue by dfaulken** [umts/incidents#98]
From today's meeting at VATCo.

**Comment by dfaulken** [comment]
Hmm, not actually sure how to do this, since it's not a static file, it's rendered through HAML. Need to look further into this.

**Comment by werebus** [comment]
I think you can still send along the desired `Content-Disposition` header in the controller: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

**Comment by dfaulken** [comment]
Thanks!
